# the theme from: https://github.com/artemsheludko/monday.git
title: vic homepage | www.whing.cn
description: "There is only one heroism in the world: to see the world as it is and to love it."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://whing.cn" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Vic Woo
tagline: AI Algorithm Engineer
about-description: Huang Wu (English name is Vic Woo), Master of Science (MSc), graduated from Institute of Statistics in School of Computer and Information, Anqing Normal University, Anhui, China. The main research directions and interests are in Machine Learning (ML), Pattern Recognition(PR) and Human Activity Recognition(HAR). Furthermore, the more attentions are paid on Big-data technology and Deep Learning, working on artificial intelligence in education about ML&DL, HAR, DIP, CV and so on. # Add Discription
pic: I.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
# Add your Email address
email: vic.woo@vip.163.com 
# Add your Phone number
phone0: 044 825 5523 
# Add your website, do not add http://
website: whing.cn
# Add your Linkedin handle
linkedin: vicwoo
# Add your Github handle
github: vic9527 
# Add your Twitter handle
twitter0: '@artemsheludko_' 

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
